# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TykSync < Formula
  desc "Command-line tool to sync Tyk API definitions with version control"
  homepage "https://tyk.io"
  version "2.2.2"
  depends_on :macos

  on_intel do
    url "https://packagecloud.io/tyk/tyk-sync/packages/anyfile/tyk-sync_2.2.2_darwin_amd64.zip/download?distro_version_id=230"
    sha256 "addc42d4cb9297718c836d4b92ff819ed9b81c8cb30cb8751147cc5545ae8e6d"

    def install
      bin.install "tyk-sync"
    end
  end
  on_arm do
    url "https://packagecloud.io/tyk/tyk-sync/packages/anyfile/tyk-sync_2.2.2_darwin_arm64.zip/download?distro_version_id=230"
    sha256 "01aba420afe9ddf1c7a2ff1e47512bfe9e4b6a3f72a7247eb0ce0eb83b404fd9"

    def install
      bin.install "tyk-sync"
    end
  end

  license :cannot_represent

  test do
    system "#{bin}/tyk-sync", "version"
  end
end
