# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tyk < Formula
  desc "Command-line interface for managing Tyk APIs and configurations"
  homepage "https://github.com/sedkis/tyk-cli"
  version "0.3.0"
  license "MIT"

  depends_on "curl"

  on_macos do
    on_intel do
      url "https://github.com/sedkis/tyk-cli/releases/download/v0.3.0/tyk-cli_0.3.0_darwin_amd64.tar.gz"
      sha256 "4afe4a8f086a0a9d56bb71a6dc028474b400e130310a6bdd2a587f8d368b96d0"

      def install
        bin.install "tyk"
      end
    end
    on_arm do
      url "https://github.com/sedkis/tyk-cli/releases/download/v0.3.0/tyk-cli_0.3.0_darwin_arm64.tar.gz"
      sha256 "80c7812d8938903be86b5a6caa98c2051ff96a94bd257fa4ecd719d5febb79f1"

      def install
        bin.install "tyk"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sedkis/tyk-cli/releases/download/v0.3.0/tyk-cli_0.3.0_linux_amd64.tar.gz"
        sha256 "5bf8cd1eb980230282afe2b3ed788d99935780abc94501d5fe148167bd0057c1"

        def install
          bin.install "tyk"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sedkis/tyk-cli/releases/download/v0.3.0/tyk-cli_0.3.0_linux_arm64.tar.gz"
        sha256 "ccf4cdc86de33b340285149b8e10f3bf8d26a62663e841476e567705dd2431e8"

        def install
          bin.install "tyk"
        end
      end
    end
  end

  test do
    system "#{bin}/tyk --version"
  end
end
